const mongoose = require('mongoose');
const Laboratory = require('./laboratory');

const buildingSchema = new mongoose.Schema({
    // building_id to be auto-generated by Mongo DB as _id
    building_code: {
        type: String,
        maxlength: 10,
        required: true
    },
    building_name: {
        type: String,
        maxlength: 45,
        required: true
    }
});

// ON DELETE CASCADE. When a building is deleted, all labs in that building is deleted
buildingSchema.pre("deleteOne", {document: true}, async function(next){
    try{
        await Laboratory.deleteMany({building_id: this._id});
        next();
    }
    catch (err){
        next(err);
    }
});

// NO NEED FOR UPDATE CASCADE since there is NO building attributes in Laboratory table

const Building = new mongoose.model("Building", buildingSchema);
module.exports = Building;