const mongoose = require('mongoose');

const classScheduleSchema = new mongoose.Schema({
    // class_schedule_id to be auto-generated by Mongo DB as _id
    class_id: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Existing_Class",
        required: true
    },
    class_day: {
        type: String,
        enum: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
        required: true
    },
    start_time: {
        type: String,
        required: true,
        match: /^([01]\d|2[0-3]):([0-5]\d)(:[0-5]\d)?$/ // HH:MM or HH:MM:SS
    },
    end_time: {
        type: String,
        required: true,
        match: /^([01]\d|2[0-3]):([0-5]\d)(:[0-5]\d)?$/ // HH:MM or HH:MM:SS
    },
});

// Means UNIQUE
classScheduleSchema.index(
    {class_id: 1, class_day: 1, start_time: 1, end_time: 1},
    {unique: true}
);

const Class_Schedule = new mongoose.model("Class_Schedule", classScheduleSchema);
module.exports = Class_Schedule;