const mongoose = require('mongoose');
const Class_Schedule = require('./class_schedule');

const existingClassSchema = new mongoose.Schema({
    // class_id auto-generated by Mongo DB as _id
    course_code: {
        type: String,
        maxlength: 20,
        required: true
    },
    section: {
        type: String,
        maxlength: 10,
        required: true
    },
    lab_id: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Laboratory",
        required: true
    }
});

// FOREIGN KEY (class_id) REFERENCES existing_class(class_id) ON DELETE CASCADE
// If a existing class is deleted, all class schedules that has that exisiting class is deleted as well.
existingClassSchema.pre("deleteOne", {document: true}, async function(next) {
    try{
        await Class_Schedule.deleteMany({class_id: this._id});
        next();
    }
    catch (err){
        next(err);
    }
});

// NO NEED FOR UPDATE CASCADE for Class Schedule since there is NO Class Schedule attributes in Existing Class table

// Means UNIQUE
existingClassSchema.index(
    {course_code: 1, section: 1},
    {unique: true}
);

const Existing_Class = new mongoose.model("Existing_Class", existingClassSchema);
module.exports = Existing_Class;