const mongoose = require('mongoose');
const Reservation = require('./reservation');
const Existing_Class = require('./existing_class');
const Restricted_Slots = require('./restricted_slots');

const laboratorySchema = new mongoose.Schema({
    // lab_id auto-generated by Mongo DB as _id
    building_id: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Building",
        required: true
    },
    room_code: {
        type: String,
        required: true,
        maxlength: 10,
        trim: true
    },
    capacity: {
        type: Number,
        required: true,
        min: 1
    },
    status: {
        type: String,
        enum: ["Active", "Maintenance", "Closed"],
        default: "Active",
        required: true
    }
});

// Means UNIQUE
laboratorySchema.index(
    {building_id: 1, room_code: 1},
    {unique: true}
);

// FOREIGN KEY (lab_id) REFERENCES laboratory(lab_id) ON DELETE
// If a laboratory is deleted, all reservations in that laboratory is deleted as well.

// FOREIGN KEY (lab_id) REFERENCES laboratory(lab_id) ON DELETE
// If a laboratory is deleted, all existing classes in that laboratory is deleted as well.

// FOREIGN KEY (lab_id) REFERENCES laboratory(lab_id) ON DELETE CASCADE
// If a laboratory is deleted, all restricted slots of that laboratory is deleted as well.
laboratorySchema.pre("deleteOne", {document: true}, async function(next) {
    try{
        await Reservation.deleteMany({lab_id: this._id});
        await Existing_Class.deleteMany({lab_id: this._id});
        await Restricted_Slots.deleteMany({lab_id: this._id});
        next();
    }
    catch (err){
        next(err);
    }
});

// NO NEED FOR UPDATE CASCADE for Reservations since there is NO reservation attributes in laboratory table
// NO NEED FOR UPDATE CASCADE for Existing Class since there is NO Existing Class attributes in laboratory table





const Laboratory = new mongoose.model("Laboratory", laboratorySchema);
module.exports = Laboratory;
