const mongoose = require('mongoose');

const reservationSchema = new mongoose.Schema({
    // reservation_id is auto-generated by MongoDB as _id
    user_id: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
        required: true
    },
    building_id: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Building",
        required: true
    },
    lab_id: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Laboratory",
        required: true
    },
    seat_id: {
        type: [mongoose.Schema.Types.ObjectId], // changed to array
        ref: "Seat",
        required: true
    },
    date_reserved: {
        type: Date,
        required: true
    },
    reserve_startTime: {
        type: String,
        required: true,
        match: /^([01]\d|2[0-3]):([0-5]\d)(:[0-5]\d)?$/ // HH:MM or HH:MM:SS
    },
    reserve_endTime: {
        type: String,
        required: true,
        match: /^([01]\d|2[0-3]):([0-5]\d)(:[0-5]\d)?$/ // HH:MM or HH:MM:SS
    },
    status: {
        type: String,
        enum: ["Ongoing", "Completed", "Cancelled", "Checked"],
        default: "Ongoing",
        required: true
    },
    is_anonymous: {
        type: Boolean,
        default: false
    }
});

// Unique index now considers the array of seats
reservationSchema.index(
    { user_id: 1, building_id: 1, lab_id: 1, seat_id: 1, date_reserved: 1, reserve_startTime: 1, reserve_endTime: 1 },
    { unique: true }
);

const Reservation = mongoose.model("Reservation", reservationSchema);
module.exports = Reservation;