const mongoose = require('mongoose');

const restrictedSlotSchema = new mongoose.Schema({
    // restricted_slot_id is auto-generated by Mongo DB as _id
    building_id: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Building",
        required: true
    },
    lab_id: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Laboratory",
        required: true
    },
    seat_id: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Seat",
        required: true
    },
    restricted_date: {
        type: Date,
        required: true
    },
    start_time: {
        type: String,
        required: true,
        match: /^([01]\d|2[0-3]):([0-5]\d)(:[0-5]\d)?$/, // HH:MM or HH:MM:SS
    },
    end_time: {
        type: String,
        required: true,
        match: /^([01]\d|2[0-3]):([0-5]\d)(:[0-5]\d)?$/, // HH:MM or HH:MM:SS
    }
});

// Means UNIQUE
restrictedSlotSchema.index(
    {bulding_id: 1, lab_id: 1, seat_id: 1, restricted_date: 1, start_time: 1, end_time: 1},
    {unique: true}
);

const Restricted_Slots = new mongoose.model("Restricted_Slots", restrictedSlotSchema);
module.exports = Restricted_Slots;