const mongoose = require('mongoose');

const seatSchema = new mongoose.Schema({
    // seat_id auto-generated by Mongo DB as _id
    building_id: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Building",
        required: true
    },
    lab_id: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Laboratory",
        required: true
    },
    seat_number: {
        type: String,
        required: true
    },
    status: {
        type: String,
        enum: ["Available", "Occupied", "Closed"],
        default: "Available",
        required: true
    }
});

const Seat = new mongoose.model("Seat", seatSchema);
module.exports = Seat;