const mongoose = require('mongoose');
const Student = require("./student");
const Admin = require("./admin");
const Reservation = require('./reservation');

// Combined admin and user schema
const userSchema = new mongoose.Schema({
    // user_id is auto-generated by Mongo DB as _id
    user_type: {
        type: String,
        enum: ["student", "admin"],
        required: true
    },
    email: {
        type: String,
        maxlength: 100,
        required: true,
        unique: true
    },
    user_password: {
        type: String,
        maxlength: 255,
        required: true
    },
    full_name: {
        type: String,
        maxlength: 100,
        required: true
    }
});

// FOREIGN KEY (user_id) REFERENCES user(user_id) ON DELETE CASCADE
// FOREIGN KEY (user_id) REFERENCES user(user_id) ON DELETE CASCADE
// If a student or admin is deleted, their row in users table is deleted as well.

// FOREIGN KEY (user_id) REFERENCES user(user_id) ON DELETE,
// If a user is deleted, all their reservations are deleted as well.
userSchema.pre("deleteOne", {document: true}, async function(next){
    try{
        // Delete from Student if exists, otherwise Admin
        const studentDeleted = await Student.deleteOne({user_id: this._id});
        if (studentDeleted.deletedCount === 0) {
            await Admin.deleteOne({user_id: this._id});
        }
        await Reservation.deleteMany({user_id: this._id});
        next();
    } 
    catch (err){
        next(err);
    }
});

// NO NEED FOR UPDATE CASCADE for Reservations since there is NO reservation attributes in users table

const User = new mongoose.model("User", userSchema);
module.exports = User;
